### ISSUE TITLE
Make all buildings clickable 

### ISSUE THREAD

**Issue by JSegovia** [UCSB-CS56-Projects/cs56-calculatewalkingtime#13]
Right now only 15 of the buildings are clickable. Make all of the buildings on campus clickable. Use LatLong.txt as reference for which buildings are missing.
200 points

**Comment by vincenicoara** [comment]
W16 OK

**Comment by vivekpatel42** [comment]
F16 OK (150 pts)

**Comment by steve-fields** [comment]
F17 OK (200 pts)

**Comment by steve-fields** [comment]
F17 CLOSED
