### ISSUE TITLE
Add off-campus buildings to the GUI

### ISSUE THREAD

**Issue by JSegovia** [UCSB-CS56-Projects/cs56-calculatewalkingtime#14]
Either find a new map with all the off-campus buildings (ex. FT, West Campus, etc.) or add a representation of them to the current map.
50 points

**Comment by vincenicoara** [comment]
W16 OK

**Comment by vivekpatel42** [comment]
F16 OK (50 pts)

**Comment by steve-fields** [comment]
Redundant issue (See Issue #20)
F17 CLOSED
