### ISSUE TITLE
Map GUI refactor

### ISSUE THREAD

**Issue by vivekpatel42** [UCSB-CS56-Projects/cs56-calculatewalkingtime#19]
MapGUI class hardcodes each checkbox on the map as a location and creates a new object inline for each. 

Refactor these hardcoded locations to another area in the code to make this class smaller/more readable.

**150 points**

**Comment by vivekpatel42** [comment]
F16 OK (150 pts)

**Comment by steve-fields** [comment]
F17 OK (150 pts)

**Comment by steve-fields** [comment]
F17 CLOSED
