### ISSUE TITLE
Not clear that too many boxes are checked

### ISSUE THREAD

**Issue by steve-fields** [UCSB-CS56-Projects/cs56-calculatewalkingtime#24]
When more than two location boxes are checked, a small text is given to you after you try to calculate the travel time. There should be a better way.  There are a few ways to improve this, none necessarily wrong:

- Not allow more than one destination to be selected and give instant, clear feedback that selecting another is not allowed
- Allow them to select a third box, but show them that one of the other boxes must be deselcted before calculating the time

**Comment by steve-fields** [comment]
F17 OK (150 pts)

**Comment by pconrad** [comment]
This one looks good.

**Comment by steve-fields** [comment]
F17 CLOSED
