### ISSUE TITLE
Create a GUI for this application!

### ISSUE THREAD

**Issue by vincenicoara** [UCSB-CS56-Projects/cs56-calculatewalkingtime#3]
You are free to design it according to your preference, but make sure all of the functionality is still there.
Worth **300 points** but the TAs/Professor will award **75 bonus points** if they feel you went above and beyond. 
- Since much of this is repetitive work, enable functionality for only 15 buildings of your choosing and comment which buildings you have decided to do when you finish this issue.

**Comment by mcaccamo** [comment]
done
