### ISSUE TITLE
Autocomplete in GUI

### ISSUE THREAD

**Issue by vincenicoara** [UCSB-CS56-Projects/cs56-calculatewalkingtime#7]
- Note: You must have completed issue #3 to do this issue. 
- In the GUI, add a search bar where the user can type in the building of his choice. A drop down will appear with possible buildings based on the input. 
- The building names that appear in the drop down should also have the building codes listed.

**300 points**

**Comment by vivekpatel42** [comment]
F16 OK (300 pts)

**Comment by steve-fields** [comment]
F17 OK (300 pts)

**Comment by steve-fields** [comment]
Work in progress for this in the wip-autocomplete branch

**Comment by steve-fields** [comment]
W18 CLOSED (partially complete)

**Comment by steve-fields** [comment]
W18 CLOSED (issue partly completed)
